name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake raylib-dev

    - name: Configure Project with CMake
      run: cmake -S . -B build

    - name: Build Project with CMake
      run: cmake --build build

    - name: Test Project
      run: cd build && ctest
